version: "3"
services:
  dev:
    build: .
    volumes:
      - .:/orville
      - stack-root:/stack-root
    working_dir: /orville
    depends_on:
      - testdb
    environment:
      TEST_CONN_STRING: "host=testdb user=orville_test"

  testdb:
    image: postgres:9.6.8
    environment:
      POSTGRES_USER: orville_test
    ports:
      - 54321:5432

volumes:
  stack-root:
